### ISSUE TITLE
希望能增加spring-data-mongodb、dubbo 、zookeeper的文档

### ISSUE THREAD

**Issue by RiwenWu** [docs4dev/docs4dev#11]

**Comment by docs4dev** [comment]
- [ZooKeeper](https://www.docs4dev.com/docs/en/zookeeper/r3.5.6/reference)
- [Spring Data MongoDB](https://www.docs4dev.com/docs/en/spring-data-mongodb/2.2.1.RELEASE/reference)

1. 中文文档只是简单的进行了机翻，暂时没时间校对，如果有兴趣，欢迎对其进行校对。
2. dubbo 已经有了官方的中文文档，所以没有添加，你可以直接在 [官网](http://dubbo.apache.org/zh-cn/) 查看
