### ISSUE TITLE
Linux-PAM手册翻译

### ISSUE THREAD

**Issue by linjialiang** [docs4dev/docs4dev#13]
你好，打扰你下，[`Linux-PAM`](http://www.linux-pam.org/Linux-PAM-html/)的手册可以翻译下吗？
非常感谢！

**Comment by docs4dev** [comment]
可以的，下次发布会添加

**Comment by docs4dev** [comment]
@linjialiang 已翻译：
- [Linux-PAM](https://www.docs4dev.com/docs/zh/linux-pam/1.1.2/reference)

**Comment by linjialiang** [comment]
非常感谢
