### ISSUE TITLE
能否提供chm或pdf文档下载

### ISSUE THREAD

**Issue by BirdWong** [docs4dev/docs4dev#14]
因为某些原因， 并不能一直连接网络， 有些工作需要脱机进行。如果只有在线文档，就无法在脱机环境下进行文档的查阅， 所以希望您能够提供脱机文档的下载， 感谢您的理解。

**Comment by docs4dev** [comment]
相关功能后续会添加的 😄

**Comment by BirdWong** [comment]
但愿能够早点上线， 不知道是否可以通过gitbook的方式进行pdf的生成，如果可以的话应该会对_pdf文档下载_功能上线提供帮助

**Comment by docs4dev** [comment]
@BirdWong  文档导出功能目前已经上线，但是目前只支持部分文档，你需要下载哪些文档？我尽量优先添加。

目前只添加了 [Spring Boot](https://www.docs4dev.com/docs/en/spring-boot/1.5.9.RELEASE/reference/boot-documentation-about.html#%E5%85%B3%E4%BA%8E%E6%96%87%E6%A1%A3) 以及 [Zookeeper](https://www.docs4dev.com/docs/en/zookeeper/r3.5.6/reference/zookeeperOver.html) 文档下载

**Comment by BirdWong** [comment]
@docs4dev mysql文档 ：）

**Comment by docs4dev** [comment]
英文版文档官方已经提供了相关下载，你可以访问以下链接直接下载，但是中文版的文档，因为全部导出的话太大了，目前的实现方式无法在保证样式的情况下整体导出，而且最近有点忙，所以这一块的实现可能还得再等一段时间了 :_)

- https://www.docs4dev.com/download?code=mysql&version=5.7&type=reference&lang=en
- https://dev.mysql.com/doc/
