### ISSUE TITLE
关于文档目录的一点小建议

### ISSUE THREAD

**Issue by MomentDerek** [docs4dev/docs4dev#19]
我最近在看sping的文档，觉得目录上相比较于官方文档有点不方便的地方，想和大佬说一下
首先是目录没有常驻，每次像跳转都要先点一下那个跳到最顶端的图标……

然后就是目录的分级显示，doc4dev的spring目录是显示到第二级的，剩下的级数就不会显示了

![image](https://user-images.githubusercontent.com/40252940/76375649-4d7a1980-6381-11ea-9f74-1816aeb48a67.png)

但是spring官方的文档会动态展开到最后一级，如下图

![image](https://user-images.githubusercontent.com/40252940/76375835-b497ce00-6381-11ea-821e-9bd14e00e912.png)

这样会给找东西的人极大的便利……其实手动展开也挺不错的，也挺简单

嗯……如果有不大方便改的话，大佬可忽略，毕竟这个文档已经帮了我们大忙了，在这里多谢大佬

我在阅读的过程中会帮忙校对的（希望大佬不要觉得烦）

**Comment by docs4dev** [comment]
感谢反馈，我会尽量优化的

**Comment by docs4dev** [comment]
@MomentDerek 
1. 关于目录常驻的问题，已经解决
2. spring 多级目录的问题，从网站设计上来说，其实是支持多级目录的，现在只显示两级菜单是因为spring 的官方文档在我抓取时只有两级目录，这个后面会优化
