### ISSUE TITLE
提供下载的mysql 5.7中文文档实际为英文原文文档

### ISSUE THREAD

**Issue by buryli** [docs4dev/docs4dev#20]
尝试下载mysql5.7中文文档，发现压缩包中存在的为英文文档，麻烦更新一下

[图片](https://user-images.githubusercontent.com/13730756/80596775-7d789b80-8a59-11ea-998d-d9d976f8ce7e.png)

**Comment by docs4dev** [comment]
因 License 问题，暂时不提供中文下载
