### ISSUE TITLE
是否可以和其他放了中文翻译的仓库合作？

### ISSUE THREAD

**Issue by LettuceBacon** [docs4dev/docs4dev#22]
## 起因
转了一圈发现你们的网站体验最棒，但是mysql文档版本不是8.0的。现发现github上有其他仓库有8.0的翻译（机翻），不知道能不能和其他人沟通一下，把翻译成果放到一起？
## 这样做的优势
1. 方便其他人贡献和搜索
docs4dev这个仓库在“xx 中文文档”的搜索结果排名靠前，且包含内容全面
2. 能像官网一样提供不同版本软件的文档

**Comment by docs4dev** [comment]
@LettuceBacon 感谢反馈，网站的设计就是能支持多版本多语言的文档，能提供一下具体的仓库吗？如果只是机翻，可以直接从官方拉取后翻译，这样比较齐全而且文档的样式也更好控制（因为本站对文档样式做了一定的优化），如果是人工校对过的文档，可以一起合作 😄

**Comment by LettuceBacon** [comment]
@docs4dev 机翻翻译效果不是很好。人工的是[https://github.com/zhyee/Mysql8.0_Reference_Manual_Translation](url)，不过好像很久没有动静了。
