### ISSUE TITLE
Global 很多地方 翻译成了全球

### ISSUE THREAD

**Issue by returnzq** [docs4dev/docs4dev#4]
如：数据访问 1.1.1. 全球(Global) Transaction
       1.1. Spring Framework的事务支持模型的优点
传统上，Java EE开发人员有两种 Transaction 管理选择：全局或本地 Transaction ，这两种 Transaction 都有很大的局限性。接下来的两节将对全球(Global)和本地 Transaction 管理进行审核，然后讨论如何进行全面和本地 Transaction 管理Spring Framework的事务管理支持解决了全局和本地事务模型的局限性。

**Comment by docs4dev** [comment]
最近会上线在线校对功能，有兴趣的话，希望到时共同合作，完善文档

**Comment by docs4dev** [comment]
@returnzq 网站已经上线了在线校对的功能 😄
