### ISSUE TITLE
spring cloud 没有这个版本？

### ISSUE THREAD

**Issue by songjiang951130** [docs4dev/docs4dev#6]
![image](https://user-images.githubusercontent.com/20123559/63163126-0f20b400-c057-11e9-8258-81cd1c511c69.png)

https://www.docs4dev.com/docs/zh/spring-cloud/Edgware.SR5/reference/multi__spring_cloud_context_application_context_services.html#spring-cloud-context%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%B8%8B%E6%96%87%E6%9C%8D%E5%8A%A1

**Comment by docs4dev** [comment]
官方文档地址：https://cloud.spring.io/spring-cloud-static/Edgware.SR5/
