### ISSUE TITLE
个人认为Beeline这个词在hive文档中不要翻译

### ISSUE THREAD

**Issue by dirtyair** [docs4dev/docs4dev#8]
https://www.docs4dev.com/docs/zh/apache-hive/3.1.1/reference
文档中Beeline CLI翻译为 *直线 CLI* 这样看起来有些奇怪，个人认为这里不要翻译beeline这个词，大家看了beeline就知道这是连接hiveserver2的客户端工具，Beeline CLI章节中有些Beeline翻译了为直线，有些没有翻译，个人认为都不要翻译。

**Comment by docs4dev** [comment]
我会更新的

**Comment by docs4dev** [comment]
@dirtyair 网站已经上线了在线校对的功能 😄
